# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/innsolit/project_lab_3/project_lab_3.cache/wt [current_project]
set_property parent.project_path C:/Users/innsolit/project_lab_3/project_lab_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/innsolit/project_lab_3/project_lab_3.srcs/sources_1/new/two_to_one_mux.sv
  C:/Users/innsolit/project_lab_3/project_lab_3.srcs/sources_1/new/four_to_one_mux.sv
  C:/Users/innsolit/project_lab_3/project_lab_3.srcs/sources_1/new/eight_to_one_mux.sv
  C:/Users/innsolit/project_lab_3/project_lab_3.srcs/sources_1/new/function_f.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/innsolit/project_lab_3/project_lab_3.srcs/constrs_1/new/cons_two_to_four_dec.xdc
set_property used_in_implementation false [get_files C:/Users/innsolit/project_lab_3/project_lab_3.srcs/constrs_1/new/cons_two_to_four_dec.xdc]

read_xdc C:/Users/innsolit/project_lab_3/project_lab_3.srcs/constrs_1/new/cons_func.xdc
set_property used_in_implementation false [get_files C:/Users/innsolit/project_lab_3/project_lab_3.srcs/constrs_1/new/cons_func.xdc]


synth_design -top function_f -part xc7a35tcpg236-1


write_checkpoint -force -noxdef function_f.dcp

catch { report_utilization -file function_f_utilization_synth.rpt -pb function_f_utilization_synth.pb }
