set_property PACKAGE_PIN W5 [get_ports clk]  	 	 	 	  
 	set_property IOSTANDARD LVCMOS33 [get_ports clk] 
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk] 

# Switches 
set_property PACKAGE_PIN V17 [get_ports {B[0]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}] 
set_property PACKAGE_PIN V16 [get_ports {B[1]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}] 
set_property PACKAGE_PIN W16 [get_ports {B[2]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}] 
set_property PACKAGE_PIN W17 [get_ports {B[3]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}] 
set_property PACKAGE_PIN W15 [get_ports {B[4]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {B[4]}] 
set_property PACKAGE_PIN V15 [get_ports {B[5]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {B[5]}] 
set_property PACKAGE_PIN W14 [get_ports {B[6]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {B[6]}] 
set_property PACKAGE_PIN W13 [get_ports {B[7]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {B[7]}] 
set_property PACKAGE_PIN V2 [get_ports {A[0]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}] 
set_property PACKAGE_PIN T3 [get_ports {A[1]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}] 
set_property PACKAGE_PIN T2 [get_ports {A[2]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}] 
set_property PACKAGE_PIN R3 [get_ports {A[3]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}] 
set_property PACKAGE_PIN W2 [get_ports {A[4]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {A[4]}] 
set_property PACKAGE_PIN U1 [get_ports {A[5]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {A[5]}] 
set_property PACKAGE_PIN T1 [get_ports {A[6]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {A[6]}] 
set_property PACKAGE_PIN R2 [get_ports {A[7]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {A[7]}] 
 	
#Buttons 
set_property PACKAGE_PIN U18 [get_ports Shift]  	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports Shift] 
set_property PACKAGE_PIN W19 [get_ports RESET]  	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports RESET] 
set_property PACKAGE_PIN T17 [get_ports Load]  	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports Load] 
                                                                 
# LEDs 
 set_property PACKAGE_PIN U16 [get_ports {sum[0]}]                      
      set_property IOSTANDARD LVCMOS33 [get_ports {sum[0]}] 
 set_property PACKAGE_PIN E19 [get_ports {sum[1]}]                      
      set_property IOSTANDARD LVCMOS33 [get_ports {sum[1]}] 
 set_property PACKAGE_PIN U19 [get_ports {sum[2]}]                      
      set_property IOSTANDARD LVCMOS33 [get_ports {sum[2]}] 
 set_property PACKAGE_PIN V19 [get_ports {sum[3]}]                      
      set_property IOSTANDARD LVCMOS33 [get_ports {sum[3]}] 
 set_property PACKAGE_PIN W18 [get_ports {sum[4]}]                      
      set_property IOSTANDARD LVCMOS33 [get_ports {sum[4]}] 
 set_property PACKAGE_PIN U15 [get_ports {sum[5]}]                      
      set_property IOSTANDARD LVCMOS33 [get_ports {sum[5]}] 
 set_property PACKAGE_PIN U14 [get_ports {sum[6]}]                      
      set_property IOSTANDARD LVCMOS33 [get_ports {sum[6]}] 
 set_property PACKAGE_PIN V14 [get_ports {sum[7]}]                      
      set_property IOSTANDARD LVCMOS33 [get_ports {sum[7]}] 