# Switches 
set_property PACKAGE_PIN V17 [get_ports {d[0]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {d[0]}] 
set_property PACKAGE_PIN V16 [get_ports {d[1]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {d[1]}] 
set_property PACKAGE_PIN W16 [get_ports {d[2]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {d[2]}] 
set_property PACKAGE_PIN W17 [get_ports {d[3]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {d[3]}] 
set_property PACKAGE_PIN W15 [get_ports {d[4]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {d[4]}] 
set_property PACKAGE_PIN V15 [get_ports {d[5]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {d[5]}] 
set_property PACKAGE_PIN W14 [get_ports {d[6]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {d[6]}] 
set_property PACKAGE_PIN W13 [get_ports {d[7]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {d[7]}] 
set_property PACKAGE_PIN V2 [get_ports {s[0]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {s[0]}] 
set_property PACKAGE_PIN T3 [get_ports {s[1]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {s[1]}] 
set_property PACKAGE_PIN T2 [get_ports {s[2]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {s[2]}] 
 	
# LEDs 
set_property PACKAGE_PIN U16 [get_ports {y}]                      
    set_property IOSTANDARD LVCMOS33 [get_ports {y}] 