# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/innsolit/traffic_lights_fsm/traffic_lights_fsm.cache/wt [current_project]
set_property parent.project_path C:/Users/innsolit/traffic_lights_fsm/traffic_lights_fsm.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv C:/Users/innsolit/traffic_lights_fsm/traffic_lights_fsm.srcs/sources_1/new/fsm_module.sv
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/innsolit/traffic_lights_fsm/traffic_lights_fsm.srcs/constrs_1/new/con1.xdc
set_property used_in_implementation false [get_files C:/Users/innsolit/traffic_lights_fsm/traffic_lights_fsm.srcs/constrs_1/new/con1.xdc]


synth_design -top fsm_module -part xc7a35tcpg236-1


write_checkpoint -force -noxdef fsm_module.dcp

catch { report_utilization -file fsm_module_utilization_synth.rpt -pb fsm_module_utilization_synth.pb }
