# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/innsolit/demo_project/demo_project.cache/wt [current_project]
set_property parent.project_path C:/Users/innsolit/demo_project/demo_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/innsolit/demo_project/demo_project.srcs/sources_1/new/datapath.sv
  C:/Users/innsolit/demo_project/demo_project.srcs/sources_1/new/control_unit.sv
  C:/Users/innsolit/demo_project/demo_project.srcs/sources_1/new/debouncer.sv
  C:/Users/innsolit/demo_project/demo_project.srcs/sources_1/new/seven_seg_disp.sv
  C:/Users/innsolit/demo_project/demo_project.srcs/sources_1/new/processor.sv
  C:/Users/innsolit/demo_project/demo_project.srcs/sources_1/new/top_module.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/innsolit/demo_project/demo_project.srcs/constrs_1/new/cnstrnt.xdc
set_property used_in_implementation false [get_files C:/Users/innsolit/demo_project/demo_project.srcs/constrs_1/new/cnstrnt.xdc]


synth_design -top top_module -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top_module.dcp

catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
